# Generated by Django 3.0.5 on 2020-04-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddataset',
            name='file_path',
        ),
    ]
