# Generated by Django 3.0.5 on 2020-04-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_uploaddataset_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddataset',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
